---
title: "Påvirker høyden inntekten?"
author:
  - Sofie Brynjelsen
  - Silje Marie Danielsen
classoption: twoside
frontsize: 12pt
linestretch: 1.5

output: html_notebook
  pdf_document:
    df_print: paged
    toc: true
    toc_depth:3
    fig_height
 html_document:
     df_print: paged
     toc: true
     toc_depth: 3
     toc_float: true
  word_document:
      df_print: paged
      toc: true
      toc_depth: 3
lang: nb-NO
scl: apa-no-ampersand.csl
---


```{r setup}
library(modelr)
library(ggplot2)
library(knitr)
library(tinytex)
library(tidyverse)
library(ggpubr)

```


#Introduksjon


#Statistikk

```{r my_data, cache=TRUE}
my_data <- modelr::heights
names(my_data)
```


#Plots
```{r}
ggplot(data=my_data, mapping=aes(x= height, y=income )) +
geom_point()


  
```
Ser variablene ut til å være normal-fordelte eller kan en transformasjon være på sin plass? Hvor kommer de svarte prikkene på rekke øverst i geom_point plottet fra?



```{r}
ggplot()+
geom_point(data=my_data, mapping=aes(x = height, y = income, colour=factor(sex)))



```
```{r}
p3 <- ggplot(data=my_data, mapping=aes())
```


#Resultater


#Konklusjon


